@url = https://8080-kqtharine-sw2510-t2ea4umj0ou.ws-us116.gitpod.io

GET {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json

{
    "nome": "pc gamer"
}

###
GET {{url}}/plataformas/8