@url = https://8080-kqtharine-sw2510-32ml4pglv4o.ws-us116.gitpod.io

GET {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json

{
    "nome": "pcgamer"
}

###
GET {{url}}/plataformas/8